learning_rate_schedule:
  - [0, 2.0e-4]
max_steps: 900_000
batch_size: 16
debug: False
max_wav_segment_lenght: 10240
use_GT: False

# LOGGING
validation_frequency: 1_000
prediction_frequency: 1_000
weights_save_frequency: 5_000
train_images_plotting_frequency: 2
keep_n_weights: 5
keep_checkpoint_every_n_hours: 12
n_steps_avg_losses: [100, 500, 1_000, 5_000]
n_predictions: 5
prediction_start_step: 1_000
audio_start_step: 5_000
audio_prediction_frequency: 5_000 # converting to glim takes time
